name: algorithmic-art
version: 1.0.0
author: "@sumulige"
description: |
  Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration.
  Use this when users request creating art using code, generative art, algorithmic art, flow fields,
  or particle systems. Create original algorithmic art rather than copying existing artists' work.

tags:
  - generative-art
  - p5js
  - creative-coding
  - visualization
  - interactive

triggers:
  - algorithmic art
  - generative art
  - p5.js
  - flow fields
  - particle systems
  - creative coding
  - procedural art

dependencies:
  - p5.js

difficulty: advanced
