name: docx
version: 1.0.0
author: "@sumulige"
description: |
  Comprehensive document creation, editing, and analysis with support for tracked changes,
  comments, formatting preservation, and text extraction. Use when working with .docx files
  for creating, modifying, or analyzing professional documents.

tags:
  - document
  - word
  - docx
  - office
  - editing
  - tracked-changes

triggers:
  - docx file
  - word document
  - create document
  - edit document
  - tracked changes
  - redline

dependencies:
  - pandoc
  - docx-js
  - defusedxml

difficulty: intermediate
