name: threejs-fundamentals
version: 1.0.0
author: "@sumulige"
description: |
  Three.js scene setup, cameras, renderer, Object3D hierarchy, coordinate systems.
  Use when setting up 3D scenes, creating cameras, configuring renderers,
  managing object hierarchies, or working with transforms.

tags:
  - threejs
  - 3d
  - webgl
  - graphics
  - visualization

triggers:
  - Three.js
  - 3D scene
  - WebGL
  - 3D graphics
  - camera setup
  - 3D rendering

dependencies:
  - three.js

difficulty: intermediate
