name: react-best-practices
version: 1.0.0
author: vercel
description: |
  React and Next.js performance optimization guidelines from Vercel Engineering.
  Use when writing, reviewing, or refactoring React/Next.js code for optimal performance.
  Contains 45 rules across 8 categories, prioritized by impact.

tags:
  - react
  - nextjs
  - performance
  - optimization
  - best-practices

triggers:
  - React performance
  - Next.js optimization
  - bundle size
  - render optimization
  - data fetching
  - React refactor

dependencies: []

difficulty: intermediate
