name: slack-gif-creator
version: 1.0.0
author: "@sumulige"
description: |
  Knowledge and utilities for creating animated GIFs optimized for Slack.
  Provides constraints, validation tools, and animation concepts.
  Use when users request animated GIFs for Slack like "make me a GIF of X doing Y".

tags:
  - gif
  - animation
  - slack
  - image
  - creative

triggers:
  - Slack GIF
  - animated GIF
  - emoji GIF
  - create GIF
  - GIF animation

dependencies:
  - pillow
  - imageio
  - numpy

difficulty: intermediate
