name: webapp-testing
version: 1.0.0
author: "@sumulige"
description: |
  Toolkit for interacting with and testing local web applications using Playwright.
  Supports verifying frontend functionality, debugging UI behavior,
  capturing browser screenshots, and viewing browser logs.

tags:
  - testing
  - playwright
  - automation
  - browser
  - qa

triggers:
  - test webapp
  - Playwright test
  - browser automation
  - UI testing
  - frontend testing

dependencies:
  - playwright

difficulty: intermediate
